// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241214005043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Robert"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sonia"
                        },
                        new
                        {
                            Id = 3,
                            UserName = "Ethan"
                        },
                        new
                        {
                            Id = 4,
                            UserName = "Brian"
                        },
                        new
                        {
                            Id = 5,
                            UserName = "Samantha"
                        });
                });

            modelBuilder.Entity("ProductAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/41Lg9iTcsDL._AC_SL1000_.jpg",
                            Price = 249.99m,
                            ProductName = "Apple AirPods Pro (2nd Generation)",
                            ProductUrl = "https://www.amazon.com/dp/B0BD7DHHJ4"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/91zCwJq2trL._AC_SL1500_.jpg",
                            Price = 348.00m,
                            ProductName = "Sony WH-1000XM5 Noise Cancelling Headphones",
                            ProductUrl = "https://www.amazon.com/dp/B09JZ5LR8M"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/91g1MwQswsL._AC_SL1500_.jpg",
                            Price = 1199.99m,
                            ProductName = "Samsung Galaxy S23 Ultra",
                            ProductUrl = "https://www.amazon.com/dp/B0BN4N1NVK"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/71hZlxQvf5L._AC_SL1500_.jpg",
                            Price = 129.95m,
                            ProductName = "Fitbit Charge 5 Fitness Tracker",
                            ProductUrl = "https://www.amazon.com/dp/B097R8FRF7"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/91g9h2yEn7L._AC_SL1500_.jpg",
                            Price = 199.99m,
                            ProductName = "Ninja Foodi 9-in-1 Pressure Cooker",
                            ProductUrl = "https://www.amazon.com/dp/B08QV5LBHT"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/91nK8fXcY9L._AC_SL1500_.jpg",
                            Price = 329.00m,
                            ProductName = "Bose QuietComfort 45 Bluetooth Headphones",
                            ProductUrl = "https://www.amazon.com/dp/B097J2DGG4"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/81Po6RSeybL._AC_SL1500_.jpg",
                            Price = 1199.99m,
                            ProductName = "Apple MacBook Air M2",
                            ProductUrl = "https://www.amazon.com/dp/B09Y3M7N6T"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/71YkttnQ9FL._AC_SL1500_.jp",
                            Price = 399.00m,
                            ProductName = "GoPro HERO11 Black Action Camera",
                            ProductUrl = "https://www.amazon.com/dp/B09D7SZMFS"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/71m0kBejd1L._AC_SL1000_.jpg",
                            Price = 99.99m,
                            ProductName = "Amazon Echo (4th Gen)",
                            ProductUrl = "https://www.amazon.com/dp/B07ZVJGZ9F"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/91YvSzYjS6L._AC_SL1500_.jpg",
                            Price = 1496.99m,
                            ProductName = "LG 55-Inch 4K OLED TV",
                            ProductUrl = "https://www.amazon.com/dp/B08GGVFV1H"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://m.media-amazon.com/images/I/71Fj7YQEX6L._AC_SL1500_.jpg",
                            Price = 499.99m,
                            ProductName = "Sony PlayStation 5 Console",
                            ProductUrl = "https://www.amazon.com/dp/B08FC5L3RG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
