// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241214235408_UserEntityUpdated")]
    partial class UserEntityUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "57CB9D5740231C0370F4BF587147ADA149392A8B6174EDB69BD92BCDB8D973C8:E227A7D7C0B2E3C0D52C2DB57FC441AE:50000:SHA256",
                            UserName = "Robert"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "47BF37887243A68951D279750A84B77F2CDAE82B447AC99C0B52D33384DF9FB4:B1F8EA2EF18C24E4EA5AF503503C0985:50000:SHA256",
                            UserName = "Sonia"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "647C77B2CFFF2BB3BE371DE8864EBAD9195979AF97ECD6DEE47E8A64221D42FC:E53E4331007CB84EF07BC583216DA047:50000:SHA256",
                            UserName = "Ethan"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "A0F5D07F914042781B141DB9DB5491371B15597F78D8641868390F08264DB3F0:B8E741E79977323746992497CF68925F:50000:SHA256",
                            UserName = "Brian"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "FE319BE40FD36ED21B4D79246AB5AD6A663D3514585F424E0E0982B15B5E4422:56817F85F6EF291D80120E6641B61327:50000:SHA256",
                            UserName = "Samantha"
                        });
                });

            modelBuilder.Entity("ProductAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SX522_.jpg",
                            Price = 199.99m,
                            ProductName = "Apple AirPods Pro (2nd Generation)",
                            ProductUrl = "https://www.amazon.com/dp/B0D1XD1ZV3"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://m.media-amazon.com/images/I/51aXvjzcukL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Price = 298.00m,
                            ProductName = "Sony WH-1000XM5 Noise Cancelling Headphones",
                            ProductUrl = "https://www.amazon.com/dp/B09XS7JWHH"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://m.media-amazon.com/images/I/71HtN4qqLZL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Price = 1149.97m,
                            ProductName = "Samsung Galaxy S23 Ultra",
                            ProductUrl = "https://www.amazon.com/dp/B0BLP2Y34S"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://m.media-amazon.com/images/I/61wn2jfhBkL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Price = 119.95m,
                            ProductName = "Fitbit Charge 5 Fitness Tracker",
                            ProductUrl = "https://www.amazon.com/dp/B0CC63GZ3R"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://m.media-amazon.com/images/I/71GhytEjuYL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
                            Price = 89.99m,
                            ProductName = "Ninja Foodi 9-in-1 Pressure Cooker",
                            ProductUrl = "https://www.amazon.com/dp/B0CDHP76FP"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://m.media-amazon.com/images/I/61JY8Eci-LL._AC_SX679_.jpg",
                            Price = 329.00m,
                            ProductName = "Bose QuietComfort 45 Bluetooth Headphones",
                            ProductUrl = "https://www.amazon.com/dp/B0CCZ26B5V"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://m.media-amazon.com/images/I/719C6bJv8jL._AC_SX522_.jpg",
                            Price = 799.00m,
                            ProductName = "Apple MacBook Air M2",
                            ProductUrl = "https://www.amazon.com/dp/B0DLHCWH55"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://m.media-amazon.com/images/I/81hqcAQdFSL._AC_SX679_.jpg",
                            Price = 358.49m,
                            ProductName = "GoPro HERO11 Black Action Camera",
                            ProductUrl = "https://www.amazon.com/dp/B087HRMHXY"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://m.media-amazon.com/images/I/81t8gScXClL._AC_SY300_SX300_.jpg",
                            Price = 54.99m,
                            ProductName = "Amazon Echo (4th Gen)",
                            ProductUrl = "https://www.amazon.com/dp/B07XKF5RM3"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://m.media-amazon.com/images/I/71O7wgely5L.__AC_SY300_SX300_QL70_FMwebp_.jpg",
                            Price = 1396.99m,
                            ProductName = "LG 55-Inch 4K OLED TV",
                            ProductUrl = "https://www.amazon.com/dp/B0BVXF72HV"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://m.media-amazon.com/images/I/61VTGdjik6L._SX522_.jpg",
                            Price = 775.00m,
                            ProductName = "Sony PlayStation 5 Console",
                            ProductUrl = "https://www.amazon.com/dp/B0CNV1DTCX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
